### ISSUE TITLE
Would you release v2.0.9 or v2.1.0?

### ISSUE THREAD

**Issue by sanemat** [cookpad/chanko#52]
`v2.0.8 on Sep 15, 2015` is too old 😭

**Comment by amatsuda** [comment]
Agreed.
We need to make 2.0.9 release from current master not just because 2.0.8 is "too old" but rather because we need a packaged gem including 068fc87aba7055dca5d7fb74fcd47c5a1aa079f1.

**Comment by taiki45** [comment]
Thanks for pushing. Just released as v2.1.0: https://rubygems.org/gems/chanko/versions/2.1.0
