### ISSUE TITLE
support for rails 6.1.0

### ISSUE THREAD

**Issue by kentarohorie** [cookpad/chanko#56]
This line not work in rails 6.1.0.
https://github.com/cookpad/chanko/blob/master/lib/chanko/loader.rb#L51

```ruby
def add_autoload_path
  ActiveSupport::Dependencies.autoload_paths << autoload_path
  ActiveSupport::Dependencies.autoload_paths.uniq!
 end
```

Because `ActiveSupport::Dependencies.autoload_paths` is frozen.

https://guides.rubyonrails.org/autoloading_and_reloading_constants.html#autoload-paths

**Comment by eagletmt** [comment]
Good catch. Could you create a pull-request?

**Comment by kentarohorie** [comment]
@eagletmt I created a pull-request.
Please review this m(_ _)m
https://github.com/cookpad/chanko/pull/57

**Comment by kentarohorie** [comment]
I resolved this issue by https://github.com/cookpad/chanko/pull/57
