### ISSUE TITLE
When using zeitwerk, eager_load fails in production mode

### ISSUE THREAD

**Issue by ikad** [cookpad/chanko#61]
This can be avoided by letting zeitwerk do the work instead of using Chanko :: Loader.
So in my project I added the following code in `config/application.rb`
```
config.before_configuration do
  Chanko::Config.eager_load = false
end
```

Is it possible to add a decision process to determine if zeitwerk is used in the next part, like #57?
https://github.com/cookpad/chanko/blob/master/lib/chanko/railtie.rb#L24
https://github.com/cookpad/chanko/blob/master/lib/chanko/railtie.rb#L30

**Comment by eudoxa** [comment]
Sorry for replying late
I fixed reported issue at this PR https://github.com/cookpad/chanko/pull/64
