### ISSUE TITLE
Rails6(開発環境)において、Viewファイル保存後のリロードで、Unit側のViewファイルの呼び出しが失敗する

### ISSUE THREAD

**Issue by eudoxa** [cookpad/chanko#69]
# 発生環境
Rails6 + development + zeitwerk及びclassicのview拡張

# 再現方法
```ruby
scope(:view) do
  function(:hello) do
    render '/hello'
  end
end
```
上記をviewファイルから呼び出した状態で、viewファイル「のみ」を保存しリロードすると、下記のエラーが発生する。
```
  [Chanko] ActionView::Template::Error - undefined method `_app_units_hello_world_views__hello_html_erb__3197552978688360732_19600' for #<ActionView::Base:0x00000000009ad8>
```

# 原因(調査中)
Rails6ではViewファイルを保存するたびにActionView::Baseを作り直すようで、Unitで事後に定義したviewファイルの追加設定が反映されない。

Rails6
```
1. Viewクラスのインスタンス(viewでのself.__id__)
	- リロード => 不変
	- Viewファイル書き換え => 変更
	- Modelファイル書き換え => 変更
2. Model/Unit
	- リロード => 不変
	- Viewファイル書き換え => 不変
	- Modelファイル書き換え => 変更
```

Rails5
```
1. Viewクラスのインスタンス(viewでのself.__id__)
	- リロード => 不変
	- Viewファイル書き換え => 不変
	- Modelファイル書き換え => 変更
3. Model/Unit
	- リロード => 不変
	- Viewファイル書き換え => 不変
	- Modelファイル書き換え => 変更
```

**Comment by eudoxa** [comment]
この問題は下記の箇所において
「@compile」の判定と、「view.compiled_method_containerの状態」が食い違う事により発生しています。
https://github.com/rails/rails/blob/6-1-stable/actionview/lib/action_view/template.rb#L238-L258

これはRails6対応のPRで書いた下記と同じ問題です
https://github.com/cookpad/chanko/pull/64#pullrequestreview-1193872010

**Comment by uasi** [comment]
Closed by #70
